echo "=== SUPABASE EDGE FUNCTION UPDATE ==="
echo "🔧 PROBLEMA: Erro de metadata do Stripe (limite de 500 caracteres excedido)"
echo "✅ SOLUÇÃO: Metadados simplificados sem booking_ids longos"
echo ""
echo "📁 ARQUIVO ATUALIZADO: supabase\functions\create-payment\index.ts"
echo ""
echo "🚀 OPÇÕES DE DEPLOY MANUAL:"
echo "1. Via Supabase Dashboard:"
echo "   - Ir para https://supabase.com/dashboard/project/rnhibdbxfbminqseayos"
echo "   - Edge Functions > create-payment"
echo "   - Copiar código de: supabase\functions\create-payment\index.ts"
echo "   - Deploy"
echo ""
echo "2. Via CLI (se disponível):"
echo "   supabase functions deploy create-payment --project-ref rnhibdbxfbminqseayos"
echo ""
echo "3. Via curl (teste da função):"
echo "   curl -X POST 'https://rnhibdbxfbminqseayos.supabase.co/functions/v1/create-payment'"
echo ""
echo "🎯 RESULTADO ESPERADO:"
echo "   - Booking recorrente funciona sem erro de metadata"
echo "   - Todas as 15 aulas são criadas corretamente"
echo "   - Log mostra: 'METADATA FIX APPLIED'"
