// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnhibdbxfbminqseayos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuaGliZGJ4ZmJtaW5xc2VheW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDMzNzgsImV4cCI6MjA2MzY3OTM3OH0.XKxVhfKNDQByuktEaJZtJkRqQyU3kvg91Ogfk2-dOjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);